const { Op } = require('sequelize');
const { SiteMedia } = require('../models');
const { saveGalleryBuffer, deleteStoredFile, toPublicPath } = require('../services/imageService');
const normalize = media => { const value = media.toJSON ? media.toJSON() : { ...media }; value.file_path = toPublicPath(value.file_path) || value.file_path; value.thumbnail = toPublicPath(value.thumbnail) || value.thumbnail; return value; };
const bool = (value, fallback = true) => value === undefined ? fallback : value === true || value === 'true' || value === '1' || value === 1;

exports.list = async (req, res) => { try { const where = {}; if (req.query.public === 'true') where.is_active = true; if (req.query.section) where.section = req.query.section; if (req.query.search) where[Op.or] = [{ name: { [Op.like]: `%${req.query.search}%` } }, { placement: { [Op.like]: `%${req.query.search}%` } }]; const rows = await SiteMedia.findAll({ where, order: [['section', 'ASC'], ['sort_order', 'ASC'], ['createdAt', 'DESC']] }); res.json({ media: rows.map(normalize) }); } catch (error) { res.status(500).json({ message: error.message }); } };
exports.get = async (req, res) => { try { const media = await SiteMedia.findByPk(req.params.id); if (!media) return res.status(404).json({ message: 'Média introuvable.' }); res.json({ media: normalize(media) }); } catch (error) { res.status(500).json({ message: error.message }); } };
exports.create = async (req, res) => { try { if (!req.file?.buffer) return res.status(400).json({ message: 'Fichier obligatoire.' }); const type = req.file.mimetype === 'video/mp4' ? 'video' : 'image'; const allowed = ['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/svg+xml', 'video/mp4']; if (!allowed.includes(req.file.mimetype)) return res.status(400).json({ message: 'Format non supporté.' }); const { name, section, placement, alt, title, description, sort_order, is_active } = req.body; if (!name || !section || !placement) return res.status(400).json({ message: 'Nom, section et emplacement obligatoires.' }); const path = await saveGalleryBuffer(req.file.buffer, req.file.mimetype, 'site'); const media = await SiteMedia.create({ name, type, section, placement, file_path: path, alt: alt || null, title: title || name, description: description || null, sort_order: Number(sort_order || 0), is_active: bool(is_active), file_size: req.file.size, created_by: req.user?.id || null }); res.status(201).json({ media: normalize(media) }); } catch (error) { res.status(500).json({ message: error.message }); } };
exports.update = async (req, res) => { try { const media = await SiteMedia.findByPk(req.params.id); if (!media) return res.status(404).json({ message: 'Média introuvable.' }); for (const key of ['name', 'section', 'placement', 'alt', 'title', 'description']) if (req.body[key] !== undefined) media[key] = req.body[key]; for (const key of ['sort_order']) if (req.body[key] !== undefined) media[key] = Number(req.body[key]); if (req.body.is_active !== undefined) media.is_active = bool(req.body.is_active, media.is_active); if (req.file?.buffer) { const next = await saveGalleryBuffer(req.file.buffer, req.file.mimetype, 'site'); deleteStoredFile(media.file_path); media.file_path = next; media.file_size = req.file.size; media.type = req.file.mimetype === 'video/mp4' ? 'video' : 'image'; } await media.save(); res.json({ media: normalize(media) }); } catch (error) { res.status(500).json({ message: error.message }); } };
exports.remove = async (req, res) => { try { const media = await SiteMedia.findByPk(req.params.id); if (!media) return res.status(404).json({ message: 'Média introuvable.' }); deleteStoredFile(media.file_path); deleteStoredFile(media.thumbnail); await media.destroy(); res.json({ message: 'Média supprimé.' }); } catch (error) { res.status(500).json({ message: error.message }); } };
exports.reorder = async (req, res) => { try { const ids = Array.isArray(req.body.ids) ? req.body.ids : []; await Promise.all(ids.map((id, index) => SiteMedia.update({ sort_order: index }, { where: { id } }))); res.json({ message: 'Ordre enregistré.' }); } catch (error) { res.status(500).json({ message: error.message }); } };
